### PR TITLE
Fix signed/unsigned warnings

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Isn't it better to use size_t as the type for strlen() and atomicio()?

**Comment by ghost** [comment]
Probably, yes.

**Comment by petterreinholdtsen** [comment]
[Bob Mottram]

> Probably, yes.

Great.  I lack the testbench to check changes at the moment.  Can you
update/replace your pull request with a tested fix using size_t?

Thank you for sending the patch, btw.  I was really glad to see someone
testing exim4-smtorp after all this time.  I have not had time to play
with it for many months. :)

## 

Happy hacking
Petter Reinholdtsen

**Comment by ghost** [comment]
It should now be updated. I'll be testing this out soon.

**Comment by petterreinholdtsen** [comment]
Look good to me. :)

**Pull request merged**
